apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2020-12-16T19:22:43Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "144"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: 8d0428cd-b628-42fa-9b39-9d79de545327
  spec:
    clusterIP: 10.15.240.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2020-12-16T19:39:21Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: web
    name: web
    namespace: default
    resourceVersion: "5086"
    selfLink: /api/v1/namespaces/default/services/web
    uid: 1aa0ef9e-3a5e-47b4-ae6e-a20e8c099c65
  spec:
    clusterIP: 10.15.245.95
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 30607
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: web
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 34.123.212.47
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
